### ISSUE TITLE
MonotonicUlid vs Ulid

### ISSUE THREAD

**Issue by nimo23** [f4b6a3/ulid-creator#24]
Can you please tell me the use cases where a _"non-monotonic"_ Ulid should be preferred over a _"monotonic"_ Ulid? I expected that the generation of a `MonotonicUlid` is much slower than a _non-monotonic_ Ulid, but according to the benchmark, `MonotonicUlid` are much faster than _non-monotonic_ Ulids created by `UlidCreator.getUlid()`.

```
Ulid_fast                              thrpt    5  34523,147 ± 1022,114  ops/ms (9.98)
Ulid_fast_toString                     thrpt    5  19161,375 ±  662,563  ops/ms
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
UlidCreator_getUlid                    thrpt    5   4276,614 ±   11,069  ops/ms (1.23)
UlidCreator_getUlid_toString           thrpt    5   3645,088 ±   85,478  ops/ms
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
UlidCreator_getMonotonicUlid           thrpt    5  32921,698 ± 1286,983  ops/ms (9.51)
UlidCreator_getMonotonicUlid_toString  thrpt    5  18541,252 ±  710,281  ops/ms
```

**Comment by fabiolimace** [comment]
I think the "non-monotonic" Ulid is the default in the specification. The other is an alternative type for those who want to create a bunch of Ulids at once in an increasing way, within a time interval that corresponds to 1 millisecond.

The default Ulid requests random bytes every time from the underlying OS. This can be a problem if Ulids are generated at a faster frequency than the operating system can provide random values. The first article below talks about a performance issue in generating random UUIDs. The second article explains very well how SecureRandom works and how it depends on the OS entropy pool.

* [Java UUID generation – Performance impact](https://blog.ycrash.io/2022/03/09/java-uuid-generation-performance-impact/)
* [Secure random number generation in JAVA](https://resources.infosecinstitute.com/topic/random-number-generation-java/)

Monotonic Ulid is faster because it only requests random bytes from the underlying OS once every millisecond. Each time it is necessary to generate a new Ulid, within this time interval, the random bits are incremented by 1. Another advantage of this type is that there is no risk of the random part being repeated in the same millisecond, that is, there is no collision risk within that interval as long as no more than 2^80 are generated. But this is only true when there is only one process generating Ulids.


I don't know many applications that use either type. The ones I know are the ones I can find here on Github with the keyword ['f4b6a3'](https://github.com/search?q=%22f4b6a3%22).

**Comment by fabiolimace** [comment]
I think I didn't express myself well. You shouldn't use the expressions "types" and "at once".

In fact, there is only 1 type of ULID. What exists in the specification are two ways to generate ULIDs. In a way the random component is regenerated every time a new ULID is requested. In the other way (the monotonic way), the random component is regenerated only once within the millisecond and incremented if a new ULID is requested within that same millisecond. But that doesn't mean that in the second way only 1 ULID will be generated per millisecond. In both ways, you can generate up to 2^80 per millisecond, which is an astronomically large number.

When I used the expression "at once" I meant "a lot" (which is reduncancy), not necessarily for pooling. But the intention of the author of the specification was different: "provide some guarantees regarding sort order". So forget what I said.

ULIDs are [partially ordered](https://en.wikipedia.org/wiki/K-sorted_sequence). That is, only the 48-bit prefix is ​​ordered. The other 80 bits are random. Therefore, the ULIDs are not ordered within this very short time span. When you increment the other 80 bits by 1, not just the prefix, but the entire identifier is sorted in ascending order. This is what the [`monotonicFactory()`](https://github.com/ULID/javascript/blob/a5831206a11636c94d4657b9e1a1354c529ee4e9/lib/index.ts#L160) factory does in the reference implementation.

Although the ULID is a simple idea, the specification leaves many gaps that we can only fill in by looking at the source code of the author's implementation. For example, I said the "non-monotonic" way is the default way because I saw it in the [last line of code in the reference implementation](https://github.com/ulid/javascript/blob/a5831206a11636c94d4657b9e1a1354c529ee4e9/lib/index.ts#L180). I suggest you take a look at the reference implementation as well. Unfortunately, the author seems to be no longer motivated in updating the specification. It's a pity because a lot of people liked his work.

In short:

* **`ULID.getUlid()`**:
    - Corresponds to the [`factory()`](https://github.com/ULID/javascript/blob/a5831206a11636c94d4657b9e1a1354c529ee4e9/lib/index.ts#L148) factory of the reference implementation;
    - It is the slowest of the three, ie it produces fewer ULIDs per time interval because it uses a cryptographically secure PRGN;
    - It is _partially_ sorted because only the 48 bits are sorted and the other 80 bits are randomly generated every time;
    - It can generate up to 2^80 ULIDs per millisecond, but the more you generate, the more entropy it consumes from the operating system;
    - There is a very small risk of the remaining 80 bits being repeated within a ms;
    - I would say that this is the preferred method as it is the safest of the three.
* **`ULID.getMonotonicUlid()`**:
    - Corresponds to the [`monotonicFactory()`](https://github.com/ULID/javascript/blob/a5831206a11636c94d4657b9e1a1354c529ee4e9/lib/index.ts#L160) factory of the reference implementation;
    - It is faster than the first one, ie it produces much more ULIDs per time interval because it simply adds 1 to the random component instead of generating it every time;
    - It is _fully_ sorted because not only the first 48 bits are sorted, but also the remaining 80 bits due to the increment of 1. I think that's why the author uses the word "monotonic". But this is only true when there is only one process generating ULIDs. If there is more than one, this advantage disappears.
    - Can also generate up to 2^80 ULIDs per millisecond, but only consumes OS entropy once every millisecond;
    - There is no risk of the remaining 80 bits being repeated within the ms, as long as no more than 2^80 are generated per ms and there is not more than one process generating ULIDs;
    - I would say this method is good for those who want high throughput, fully ordered values, and some security, although it is easy to find the next value within a ms.
* **`ULID.fast()`**:
    - It is similar to the `ULID.getUlid()` method, ie it corresponds to the `ULID()` factory of the reference implementation;
    - It is much faster than the first one because it uses a PRGN of the [Xorshift](https://en.wikipedia.org/wiki/Xorshift) type, which is not cryptographically secure, but is very efficient and passes a [RNG testing suite](https://webhome.phy.duke.edu/~rgb/General/dieharder.php) according to the documentation;
    - It is _partially_ sorted, just like the first one, because only the 48 bits are sorted and the other 80 bits are randomly generated every time;
    - It can also generate up to 2^80 ULIDs per millisecond, and does not consume the entropy of the operating system, as the random numbers are only calculated, without depending on entropy gathering;
    - There is also a very small risk of the remaining 80 bits being repeated within a ms;
    - I would say this might be preferred if throughput is more important than safety.

**Comment by fabiolimace** [comment]
I implemented now the `Ulid.fastMonotonic()` method to test whether it is worth having a monotonic generator with `SplittableRandom`.

```java
	// updates must be synchronized
	private static long lastTime = -1;
	private static Ulid lastUlid = null;

	public static synchronized Ulid fastMonotonic() {
		final long time = System.currentTimeMillis();
		if (time == lastTime) {
			lastUlid = lastUlid.increment();
		} else {
			lastUlid = fast();
		}
		lastTime = time;
		return new Ulid(lastUlid);
	}
```

But the throughput of `Ulid.fastMonotonic()` is worse (-26% less) than `Ulid.fast()`;

```
------------------------------------------------------------------------
Benchmark                       Mode  Cnt      Score      Error   Units
------------------------------------------------------------------------
Throughput.Ulid_fast           thrpt    5  32754.654 ± 1276.342  ops/ms 
Throughput.Ulid_fastMonotonic  thrpt    5  24322.012 ± 1260.401  ops/ms (-26%)
------------------------------------------------------------------------
```

As you can see there is no performance gain, but contrary to what we expect. So I think it's not useful because you have to *sync* the `Ulid.fastMonotonic()` method.
