### ISSUE TITLE
breaking changes in 3.0.1

### ISSUE THREAD

**Issue by nimo23** [f4b6a3/ulid-creator#8]
Hi,

I have updated to 3.0.1 and it seems there are breaking changes:

```
//before:
UlidCreator.getUlidString();
```

```
//now:
UlidCreator.getUlid().toString();
UlidCreator.getUlid().toLowerCase(); // this is nice! thanks!
```

The package com.github.f4b6a3.ulid.util with `UlidUtil` does not exist anymore:

```
// before
UlidUtil.extractInstant(ulid).atZone(ZoneId.systemDefault());
```

```
// now
Instant.ofEpochMilli(Ulid.from(ulid).getTime()).atZone(ZoneId.systemDefault());
```

I think, the above code are ok.

Is there anywhere  a changelog in the repo (at least for breaking api changes)?

**Comment by nimo23** [comment]
Ok I think reading the log is sufficient: 

https://github.com/f4b6a3/ulid-creator/commits/master 

It's good to have only one tiny lib, no need for additional util lib. Maybe you can include a simple class`UlidUtil.class` in future within the Ulid-package (for common things like `UlidUtil.extractInstant()`).

**Comment by fabiolimace** [comment]
@nimo23 ,

The `Ulid` object knows how to extract the `Instant`. You can use `ulid.getInstant()` instead of `ulid.getTime()` to obtain a `ZonedDateTime`.

See this example:

```java
    Ulid.from("0123456789ABCDEFGHJKMNPQRS").getInstant().atZone(ZoneId.systemDefault());
//  |---------------parse-----------------|-get instant-|-----get zoned date time------|
```

Sorry! This repository must have a changelog.

In the next version, I will create a file to list the relevant changes in this repo since its beginning.
